// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET.Starter.DataAccess.SqlServer;

#nullable disable

namespace NET.Starter.DataAccess.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Organization.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BranchTimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branches", "Organization");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Organization.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("Companies", "Organization");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("Permissions", "Security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6659f17a-c52e-4ec3-847b-46866a3b2abf"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "MyPermission",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("69821b03-b132-4d35-88f0-5502908d50fa"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "IamAdministrator",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a0d9d4d0-1b6f-4e4c-8e5e-a7c6a3b2abf1"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Permission.View",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1a010b41-b5bf-4e15-8042-94bee253c835"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Role.Menu",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e298741f-3027-4299-bf56-66bd712219e0"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Role.View",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a8b4b425-8827-4fde-b2c5-1fc3e059f061"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Role.Create",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ef4baa13-1ed0-4284-8a77-2f6e315aecf8"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Role.Update",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b3a934db-1d2b-40fd-b6df-00b9594637ce"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.Role.Delete",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("11183f54-13f3-4c4c-b484-bd170342ca70"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.User.Menu",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7d8b693b-a21f-4f7e-a0f9-b1f80a86e0bd"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.User.View",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f8568aa0-aae2-4ed0-9783-b75ff180ebdf"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.User.Create",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1bfb9a81-0f01-4981-b4d5-fce12f8b4d4d"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.User.Update",
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3c390638-d417-421a-a99f-611591c07a4d"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionCode = "Security.User.Delete",
                            RowStatus = 0
                        });
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("Roles", "Security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            RoleCode = "Administrator",
                            RowStatus = 0
                        });
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("RolePermissions", "Security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("971cf134-1f3e-4719-9d56-e60ed967a117"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("6659f17a-c52e-4ec3-847b-46866a3b2abf"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("02abe492-24b8-4a90-af18-3a282f9fcc85"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("69821b03-b132-4d35-88f0-5502908d50fa"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("19dfa24e-a82a-449d-a1ce-11456ee5322c"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("a0d9d4d0-1b6f-4e4c-8e5e-a7c6a3b2abf1"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2f0e1598-1ba3-495d-9ebe-673b15512c60"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("1a010b41-b5bf-4e15-8042-94bee253c835"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f324ee94-14d8-4fab-a703-dbe0cecfdf30"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("e298741f-3027-4299-bf56-66bd712219e0"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("58df83d3-2f40-450a-86d2-604dfa27fe35"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("a8b4b425-8827-4fde-b2c5-1fc3e059f061"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("223c7549-ddcc-4d05-95dc-9336c76a3e57"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("ef4baa13-1ed0-4284-8a77-2f6e315aecf8"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c28724cb-c0c1-462c-8a71-3161dc638920"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("b3a934db-1d2b-40fd-b6df-00b9594637ce"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b6f275c7-1732-4289-90bc-30b75dfdb165"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("11183f54-13f3-4c4c-b484-bd170342ca70"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6344bbaf-73cb-4f5e-8250-2f8130f062de"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("7d8b693b-a21f-4f7e-a0f9-b1f80a86e0bd"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c3b9b0ba-9e9b-4db0-a66a-13412c77002f"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("f8568aa0-aae2-4ed0-9783-b75ff180ebdf"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("eeb6d346-4e4b-4273-b030-9a15218bf037"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("1bfb9a81-0f01-4981-b4d5-fce12f8b4d4d"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c686e3ae-9a80-4474-872a-33340d19961f"),
                            Created = new DateTime(2025, 2, 12, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            PermissionId = new Guid("3c390638-d417-421a-a99f-611591c07a4d"),
                            RoleId = new Guid("3bafc714-4aa5-4fc3-8542-f4eeb798f918"),
                            RowStatus = 0
                        });
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BadPasswordCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("Users", "Security");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("UserCompanies", "Security");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompanyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserCompanyId", "RoleId")
                        .IsUnique()
                        .HasFilter("[RowStatus] = 0");

                    b.ToTable("UserCompanyRoles", "Security");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Organization.Branch", b =>
                {
                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Organization.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.RolePermission", b =>
                {
                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Security.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Security.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompany", b =>
                {
                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Organization.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Security.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompanyRole", b =>
                {
                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Security.Role", "Role")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompany", "UserCompany")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("UserCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserCompany");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Organization.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserCompanyRoles");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.User", b =>
                {
                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("NET.Starter.DataAccess.SqlServer.Models.Security.UserCompany", b =>
                {
                    b.Navigation("UserCompanyRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
