# Menggunakan SDK .NET 8 sebagai build environment
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 7000

ENV ASPNETCORE_URLS="http://+:7000"
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["NET.Starter.Web/NET.Starter.Web.csproj", "NET.Starter.Web/"]

# Restore dependencies
RUN dotnet restore "NET.Starter.Web/NET.Starter.Web.csproj"

# Copy semua kode sumber
COPY . .

# Build project dengan referensinya
RUN dotnet build "NET.Starter.Web/NET.Starter.Web.csproj" -c Release -o /app/build

FROM build AS publish
# Publish dengan referensi project
RUN dotnet publish "NET.Starter.Web/NET.Starter.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "NET.Starter.Web.dll"]

